# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Plate.create({print_name:, scientific_name:, plate_number:, medium:, price:, number_of_prints:, description:})
Plate.create({ print_name: "Wild Turkey", scientific_name: "Meleagris Gallopavo", plate_number: "I", medium: "Glicee Print", price: 1200, number_of_prints: 20, description: "The wild turkey is an upland ground bird native to North America, one of two extant species of turkey, and the heaviest member of the diverse Galliformes. It is the same species as the domestic turkey, which was originally derived from a southern Mexican subspecies of wild turkey.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-1%2C-Wild-Turkey-final.jpg" })
Plate.create({ print_name: "Yellow-billed Cuckoo", scientific_name: "Coccyzus Americanus", plate_number: "II", medium: "Glicee Print", price: 800, number_of_prints: 10, description: "The yellow-billed cuckoo is a cuckoo. Common folk-names for this bird in the southern United States are rain crow and storm crow. These likely refer to the bird's habit of calling on hot days, often presaging rain or thunderstorms.", image_url: "https://df0bd6h5ujoev.cloudfront.net/plate-2-yellow-billed-cuckoo-final.jpg" })
Plate.create({ print_name: "Prothonotary Warbler", scientific_name: "Protonotaria Citrea", plate_number: "III", medium: "Glicee Print", price: 600, number_of_prints: 10, description: "The prothonotary warbler is a small songbird of the New World warbler family. It is the only member of the genus Protonotaria.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-3%2C-Prothronolary-Warbler-final.jpg" })
Plate.create({ print_name: "Purple Finch", scientific_name: "Haemorhous Purpureus", plate_number: "IV", medium: "Glicee Print", price: 600, number_of_prints: 10, description: "This species and the other 'American rosefinches' were formerly included with the rosefinches of Eurasia in the genus Carpodacus; however, the three North American species are not closely related to the rosefinches of the Old World, and have thus been moved to the genus Haemorhous by most taxonomic authorities.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-4%2C-Purple-Finch-final.jpg" })
Plate.create({ print_name: "Bonaparte's Flycatcher", scientific_name: "Cardellina Canadensis", plate_number: "V", medium: "Glicee Print", price: 800, number_of_prints: 10, description: "Whilst I have the pleasure of honoring this beautiful new species with the name of so distinguished a naturalist as CHARLES LUCIEN BONAPARTE, Prince of Musignano, I regret that I am unable to give any account of its habits, or even of its manner of flight, and must therefore confine my remarks upon it within very brief space.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-5-Bonaparte%27s%20Flycatcher%20final.jpg" })
Plate.create({ print_name: "Great American Hen & Young", scientific_name: "Meleagris gallopavo", plate_number: "VI", medium: "Glicee Print", price: 950, number_of_prints: 15, description: "A female turkey is called a hen, and she is quite different from her flamboyant male counterpart in this dimorphic species. Most hens also lack the chest beard, but about 10-15 percent of older female wild turkeys will develop this feature. In general, hens are also much smaller than toms.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-6%2C-Great-American-Hen-%26-Young-final.jpg" })
Plate.create({ print_name: "Purple Grakle, or Common Crow Blackbird", scientific_name: "Quiscalus quiscula", plate_number: "VII", medium: "Glicee Print", price: 900, number_of_prints: 15, description: "Common Grackles are blackbirds that look like they've been slightly stretched. They're taller and longer tailed than a typical blackbird, with a longer, more tapered bill and glossy-iridescent bodies. Grackles walk around lawns and fields on their long legs or gather in noisy groups high in trees, typically evergreens.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-7%2C-Purple-Grakle-final.jpg" })
Plate.create({ print_name: "White throated Sparrow", scientific_name: "Zonotrichia albicollis", plate_number: "VIII", medium: "Glicee Print", price: 600, number_of_prints: 10, description: "Crisp facial markings make the White-throated Sparrow an attractive bird as well as a hopping, flying anatomy lesson. There’s the black eyestripe, the white crown and supercilium, the yellow lores, the white throat bordered by a black whisker, or malar stripe. They’re also a great entrée into the world of birdsong, with their pretty, wavering whistle of Oh-sweet-canada. These forest sparrows breed mostly across Canada, but they’re familiar winter birds across most of eastern and southern North America and California.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-8%2C-White-Throated-Sparrow-final.jpg" })
Plate.create({ print_name: "Selby's Fly Catcher", scientific_name: "Setophaga citrina", plate_number: "IX", medium: "Glicee Print", price: 550, number_of_prints: 10, description: "Plumage blended, soft and glossy. The beak margined at the base with long spreading bristles. Wings of moderate length, third quill longest, second and first little shorter, the other quills graduated. Tail rather long, forked when closed, rounded when spread, the feathers acuminate.", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-9%2C-Selby%27s-Fly-Catcher-final.jpg" })
Plate.create({ print_name: "Brown Lark", scientific_name: "Anthus Aquaticus", plate_number: "X", medium: "Glicee Print", price: 700, number_of_prints: 10, description: "The brown songlark (Cincloramphus cruralis), also Australian songlark, is a small passerine bird found throughout much of Australia. ", image_url: "https://df0bd6h5ujoev.cloudfront.net/Plate-10%2C-Brown-Lark-final.jpg" })

User.create({ first_name: "Neal", last_name: "Conway", email: "conwanea@gmail.com", phone_number: "608-290-1838", street_address: "1447 W. Birchwood Ave.", state: "Illinois", zip_code: "60626", password: "password", city: "Chicago"})
User.create({ first_name: "Roy", last_name: "Devilsbeard", email: "devilsbeard@example.com", phone_number: "238-230-5509", street_address: "17 W. Woods St.", state: "Wisconsin", zip_code: "53511", password: "password", city:"Beloit"})
User.create({ first_name: "Tom", last_name: "Nook", email: "tomnook@example.com", phone_number: "987-566-3232", street_address: "6454 S. Germ St.", state: "Arkansas", zip_code: "71601", password: "password", city:"Pine Bluff"})

Order.create({ subtotal: 2000, tax: 125, total: 2125, user_id: 2})
Order.create({ subtotal: 1250, tax: 78.13, total: 1328.13, user_id: 1})
Order.create({ subtotal: 1750, tax: 109.38, total: 1859.38, user_id: 3})
Order.create({ subtotal: 1900, tax: 118.75, total: 2018.75, user_id: 1})

CartedProduct.create({ status: "Pending", user_id: 2, product_id: 1, quantity: 1, order_id: 1})
CartedProduct.create({ status: "Pending", user_id: 2, product_id: 5, quantity: 1, order_id: 1})
CartedProduct.create({ status: "Pending", user_id: 1, product_id: 9, quantity: 1, order_id: 2})
CartedProduct.create({ status: "Pending", user_id: 1, product_id: 10, quantity: 1, order_id: 2})
CartedProduct.create({ status: "Pending", user_id: 3, product_id: 2, quantity: 1, order_id: 3})
CartedProduct.create({ status: "Pending", user_id: 3, product_id: 6, quantity: 1, order_id: 3})
CartedProduct.create({ status: "Pending", user_id: 4, product_id: 3, quantity: 1, order_id: 4})
CartedProduct.create({ status: "Pending", user_id: 4, product_id: 4, quantity: 1, order_id: 4})
CartedProduct.create({ status: "Pending", user_id: 4, product_id: 10, quantity: 1, order_id: 4})